#pragma once

#include <unordered_map>

enum KB_KEY {
    KB_LIST_START = 0x01,
	KB_LBUTTON = 0x01,
    KB_RBUTTON = 0x02,
    KB_CANCEL = 0x03,
    KB_MBUTTON = 0x04,
    KB_XBUTTON1 = 0x05,
    KB_XBUTTON2 = 0x06,
    KB_0x07 = 0x07,
    KB_BACK = 0x08,
    KB_TAB = 0x09,
    KB_0x0A = 0x0A,
    KB_0x0B = 0x0B,
    KB_CLEAR = 0x0C,
    KB_RETURN = 0x0D,
    KB_0x0E = 0x0E,
    KB_0x0F = 0x0F,
    KB_SHIFT = 0x10,
    KB_CONTROL = 0x11,
    KB_MENU = 0x12,
    KB_PAUSE = 0x13,
    KB_CAPITAL = 0x14,
    KB_KANA = 0x15,
    KB_0x16 = 0x16,
    KB_JUNJA = 0x17,
    KB_FINAL = 0x18,
    KB_HANJA = 0x19,
    KB_0x1A = 0x1A,
    KB_ESCAPE = 0x1B,
    KB_CONVERT = 0x1C,
    KB_NONCONVERT = 0x1D,
    KB_ACCEPT = 0x1E,
    KB_MODECHANGE = 0x1F,
    KB_SPACE = 0x20,
    KB_PRIOR = 0x21,
    KB_NEXT = 0x22,
    KB_END = 0x23,
    KB_HOME = 0x24,
    KB_LEFT = 0x25,
    KB_UP = 0x26,
    KB_RIGHT = 0x27,
    KB_DOWN = 0x28,
    KB_SELECT = 0x29,
    KB_PRINT = 0x2A,
    KB_EXECUTE = 0x2B,
    KB_SNAPSHOT = 0x2C,
    KB_INSERT = 0x2D,
    KB_DELETE = 0x2E,
    KB_HELP = 0x2F,
    KB_0 = 0x30,
    KB_1 = 0x31,
    KB_2 = 0x32,
    KB_3 = 0x33,
    KB_4 = 0x34,
    KB_5 = 0x35,
    KB_6 = 0x36,
    KB_7 = 0x37,
    KB_8 = 0x38,
    KB_9 = 0x39,
    KB_0x3A = 0x3A,
    KB_0x3B = 0x3B,
    KB_0x3C = 0x3C,
    KB_0x3D = 0x3D,
    KB_0x3E = 0x3E,
    KB_0x3F = 0x3F,
    KB_0x40 = 0x40,
    KB_A = 0x41,
    KB_B = 0x42,
    KB_C = 0x43,
    KB_D = 0x44,
    KB_E = 0x45,
    KB_F = 0x46,
    KB_G = 0x47,
    KB_H = 0x48,
    KB_I = 0x49,
    KB_J = 0x4A,
    KB_K = 0x4B,
    KB_L = 0x4C,
    KB_M = 0x4D,
    KB_N = 0x4E,
    KB_O = 0x4F,
    KB_P = 0x50,
    KB_Q = 0x51,
    KB_R = 0x52,
    KB_S = 0x53,
    KB_T = 0x54,
    KB_U = 0x55,
    KB_V = 0x56,
    KB_W = 0x57,
    KB_X = 0x58,
    KB_Y = 0x59,
    KB_Z = 0x5A,
    KB_LWIN = 0x5B,
    KB_RWIN = 0x5C,
    KB_APPS = 0x5D,
    KB_0x5E = 0x5E,
    KB_SLEEP = 0x5F,
    KB_NUMPAD0 = 0x60,
    KB_NUMPAD1 = 0x61,
    KB_NUMPAD2 = 0x62,
    KB_NUMPAD3 = 0x63,
    KB_NUMPAD4 = 0x64,
    KB_NUMPAD5 = 0x65,
    KB_NUMPAD6 = 0x66,
    KB_NUMPAD7 = 0x67,
    KB_NUMPAD8 = 0x68,
    KB_NUMPAD9 = 0x69,
    KB_MULTIPLY = 0x6A,
    KB_ADD = 0x6B,
    KB_SEPARATOR = 0x6C,
    KB_SUBTRACT = 0x6D,
    KB_DECIMAL = 0x6E,
    KB_DIVIDE = 0x6F,
    KB_F1 = 0x70,
    KB_F2 = 0x71,
    KB_F3 = 0x72,
    KB_F4 = 0x73,
    KB_F5 = 0x74,
    KB_F6 = 0x75,
    KB_F7 = 0x76,
    KB_F8 = 0x77,
    KB_F9 = 0x78,
    KB_F10 = 0x79,
    KB_F11 = 0x7A,
    KB_F12 = 0x7B,
    KB_F13 = 0x7C,
    KB_F14 = 0x7D,
    KB_F15 = 0x7E,
    KB_F16 = 0x7F,
    KB_F17 = 0x80,
    KB_F18 = 0x81,
    KB_F19 = 0x82,
    KB_F20 = 0x83,
    KB_F21 = 0x84,
    KB_F22 = 0x85,
    KB_F23 = 0x86,
    KB_F24 = 0x87,
    KB_0x88 = 0x88,
    KB_0x89 = 0x89,
    KB_0x8A = 0x8A,
    KB_0x8B = 0x8B,
    KB_0x8C = 0x8C,
    KB_0x8D = 0x8D,
    KB_0x8E = 0x8E,
    KB_0x8F = 0x8F,
    KB_NUMLOCK = 0x90,
    KB_SCROLL = 0x91,
    KB_0x92 = 0x92,
    KB_0x93 = 0x93,
    KB_0x94 = 0x94,
    KB_0x95 = 0x95,
    KB_0x96 = 0x96,
    KB_0x97 = 0x97,
    KB_0x98 = 0x98,
    KB_0x99 = 0x99,
    KB_0x9A = 0x9A,
    KB_0x9B = 0x9B,
    KB_0x9C = 0x9C,
    KB_0x9D = 0x9D,
    KB_0x9E = 0x9E,
    KB_0x9F = 0x9F,
    KB_LSHIFT = 0xA0,
    KB_RSHIFT = 0xA1,
    KB_LCONTROL = 0xA2,
    KB_RCONTROL = 0xA3,
    KB_LMENU = 0xA4,
    KB_RMENU = 0xA5,
    KB_BROWSER_BACK = 0xA6,
    KB_BROWSER_FORWARD = 0xA7,
    KB_BROWSER_REFRESH = 0xA8,
    KB_BROWSER_STOP = 0xA9,
    KB_BROWSER_SEARCH = 0xAA,
    KB_BROWSER_FAVORITES = 0xAB,
    KB_BROWSER_HOME = 0xAC,
    KB_VOLUME_MUTE = 0xAD,
    KB_VOLUME_DOWN = 0xAE,
    KB_VOLUME_UP = 0xAF,
    KB_MEDIA_NEXT_TRACK = 0xB0,
    KB_MEDIA_PREV_TRACK = 0xB1,
    KB_MEDIA_STOP = 0xB2,
    KB_MEDIA_PLAY_PAUSE = 0xB3,
    KB_LAUNCH_MAIL = 0xB4,
    KB_LAUNCH_MEDIA_SELECT = 0xB5,
    KB_LAUNCH_APP1 = 0xB6,
    KB_LAUNCH_APP2 = 0xB7,
    KB_0xB8 = 0xB8,
    KB_0xB9 = 0xB9,
    KB_OEM_1 = 0xBA,
    KB_OEM_PLUS = 0xBB,
    KB_OEM_COMMA = 0xBC,
    KB_OEM_MINUS = 0xBD,
    KB_OEM_PERIOD = 0xBE,
    KB_OEM_2 = 0xBF,
    KB_OEM_3 = 0xC0,
    KB_0xC1 = 0xC1,
    KB_0xC2 = 0xC2,
    KB_0xC3 = 0xC3,
    KB_0xC4 = 0xC4,
    KB_0xC5 = 0xC5,
    KB_0xC6 = 0xC6,
    KB_0xC7 = 0xC7,
    KB_0xC8 = 0xC8,
    KB_0xC9 = 0xC9,
    KB_0xCA = 0xCA,
    KB_0xCB = 0xCB,
    KB_0xCC = 0xCC,
    KB_0xCD = 0xCD,
    KB_0xCE = 0xCE,
    KB_0xCF = 0xCF,
    KB_0xD0 = 0xD0,
    KB_0xD1 = 0xD1,
    KB_0xD2 = 0xD2,
    KB_0xD3 = 0xD3,
    KB_0xD4 = 0xD4,
    KB_0xD5 = 0xD5,
    KB_0xD6 = 0xD6,
    KB_0xD7 = 0xD7,
    KB_0xD8 = 0xD8,
    KB_0xD9 = 0xD9,
    KB_0xDA = 0xDA,
    KB_OEM_4 = 0xDB,
    KB_OEM_5 = 0xDC,
    KB_OEM_6 = 0xDD,
    KB_OEM_7 = 0xDE,
    KB_OEM_8 = 0xDF,
    KB_0xE0 = 0xE0,
    KB_0xE1 = 0xE1,
    KB_OEM_102 = 0xE2,
    KB_0xE3 = 0xE3,
    KB_0xE4 = 0xE4,
    KB_PROCESSKEY = 0xE5,
    KB_0xE6 = 0xE6,
    KB_PACKET = 0xE7,
    KB_0xE8 = 0xE8,
    KB_0xE9 = 0xE9,
    KB_0xEA = 0xEA,
    KB_0xEB = 0xEB,
    KB_0xEC = 0xEC,
    KB_0xED = 0xED,
    KB_0xEE = 0xEE,
    KB_0xEF = 0xEF,
    KB_0xF0 = 0xF0,
    KB_0xF1 = 0xF1,
    KB_0xF2 = 0xF2,
    KB_0xF3 = 0xF3,
    KB_0xF4 = 0xF4,
    KB_0xF5 = 0xF5,
    KB_ATTN = 0xF6,
    KB_CRSEL = 0xF7,
    KB_EXSEL = 0xF8,
    KB_EREOF = 0xF9,
    KB_PLAY = 0xFA,
    KB_ZOOM = 0xFB,
    KB_0xFC = 0xFC,
    KB_PA1 = 0xFD,
    KB_OEM_CLEAR = 0xEF,
    KB_0xFF = 0xFF,
	KB_LIST_END = 0xFF
};

static std::unordered_map<uint8_t, const char *> g_vecKeys = {
        {KB_LBUTTON,             "Left Mouse"},
        {KB_RBUTTON,             "Right Mouse"},
        {KB_CANCEL,              "CANCEL"},
        {KB_MBUTTON,             "MBUTTON"},
        {KB_XBUTTON1,            "XBUTTON1"},
        {KB_XBUTTON2,            "XBUTTON2"},
        {KB_0x07,                "0x07"},
        {KB_BACK,                "BACK"},
        {KB_TAB,                 "TAB"},
        {KB_0x0A,                "0x0A"},
        {KB_0x0B,                "0x0B"},
        {KB_CLEAR,               "CLEAR"},
        {KB_RETURN,              "RETURN"},
        {KB_0x0E,                "0x0E"},
        {KB_0x0F,                "0x0F"},
        {KB_SHIFT,               "SHIFT"},
        {KB_CONTROL,             "CONTROL"},
        {KB_MENU,                "ALT"},
        {KB_PAUSE,               "PAUSE"},
        {KB_CAPITAL,             "CAPITAL"},
        {KB_KANA,                "KANA"},
        {KB_0x16,                "0x16"},
        {KB_JUNJA,               "JUNJA"},
        {KB_FINAL,               "FINAL"},
        {KB_HANJA,               "HANJA"},
        {KB_0x1A,                "0x1A"},
        {KB_ESCAPE,              "ESCAPE"},
        {KB_CONVERT,             "CONVERT"},
        {KB_NONCONVERT,          "NONCONVERT"},
        {KB_ACCEPT,              "ACCEPT"},
        {KB_MODECHANGE,          "MODECHANGE"},
        {KB_SPACE,               "SPACE"},
        {KB_PRIOR,               "PRIOR"},
        {KB_NEXT,                "NEXT"},
        {KB_END,                 "END"},
        {KB_HOME,                "HOME"},
        {KB_LEFT,                "LEFT"},
        {KB_UP,                  "UP"},
        {KB_RIGHT,               "RIGHT"},
        {KB_DOWN,                "DOWN"},
        {KB_SELECT,              "SELECT"},
        {KB_PRINT,               "PRINT"},
        {KB_EXECUTE,             "EXECUTE"},
        {KB_SNAPSHOT,            "SNAPSHOT"},
        {KB_INSERT,              "INSERT"},
        {KB_DELETE,              "DELETE"},
        {KB_HELP,                "HELP"},
        {KB_0,                   "0"},
        {KB_1,                   "1"},
        {KB_2,                   "2"},
        {KB_3,                   "3"},
        {KB_4,                   "4"},
        {KB_5,                   "5"},
        {KB_6,                   "6"},
        {KB_7,                   "7"},
        {KB_8,                   "8"},
        {KB_9,                   "9"},
        {KB_0x3A,                "0x3A"},
        {KB_0x3B,                "0x3B"},
        {KB_0x3C,                "0x3C"},
        {KB_0x3D,                "0x3D"},
        {KB_0x3E,                "0x3E"},
        {KB_0x3F,                "0x3F"},
        {KB_0x40,                "0x40"},
        {KB_A,                   "A"},
        {KB_B,                   "B"},
        {KB_C,                   "C"},
        {KB_D,                   "D"},
        {KB_E,                   "E"},
        {KB_F,                   "F"},
        {KB_G,                   "G"},
        {KB_H,                   "H"},
        {KB_I,                   "I"},
        {KB_J,                   "J"},
        {KB_K,                   "K"},
        {KB_L,                   "L"},
        {KB_M,                   "M"},
        {KB_N,                   "N"},
        {KB_O,                   "O"},
        {KB_P,                   "P"},
        {KB_Q,                   "Q"},
        {KB_R,                   "R"},
        {KB_S,                   "S"},
        {KB_T,                   "T"},
        {KB_U,                   "U"},
        {KB_V,                   "V"},
        {KB_W,                   "W"},
        {KB_X,                   "X"},
        {KB_Y,                   "Y"},
        {KB_Z,                   "Z"},
        {KB_LWIN,                "Left WIN"},
        {KB_RWIN,                "Right WIN"},
        {KB_APPS,                "APPS"},
        {KB_0x5E,                "0x5E"},
        {KB_SLEEP,               "SLEEP"},
        {KB_NUMPAD0,             "NUMPAD0"},
        {KB_NUMPAD1,             "NUMPAD1"},
        {KB_NUMPAD2,             "NUMPAD2"},
        {KB_NUMPAD3,             "NUMPAD3"},
        {KB_NUMPAD4,             "NUMPAD4"},
        {KB_NUMPAD5,             "NUMPAD5"},
        {KB_NUMPAD6,             "NUMPAD6"},
        {KB_NUMPAD7,             "NUMPAD7"},
        {KB_NUMPAD8,             "NUMPAD8"},
        {KB_NUMPAD9,             "NUMPAD9"},
        {KB_MULTIPLY,            "MULTIPLY"},
        {KB_ADD,                 "ADD"},
        {KB_SEPARATOR,           "SEPARATOR"},
        {KB_SUBTRACT,            "SUBTRACT"},
        {KB_DECIMAL,             "DECIMAL"},
        {KB_DIVIDE,              "DIVIDE"},
        {KB_F1,                  "F1"},
        {KB_F2,                  "F2"},
        {KB_F3,                  "F3"},
        {KB_F4,                  "F4"},
        {KB_F5,                  "F5"},
        {KB_F6,                  "F6"},
        {KB_F7,                  "F7"},
        {KB_F8,                  "F8"},
        {KB_F9,                  "F9"},
        {KB_F10,                 "F10"},
        {KB_F11,                 "F11"},
        {KB_F12,                 "F12"},
        {KB_F13,                 "F13"},
        {KB_F14,                 "F14"},
        {KB_F15,                 "F15"},
        {KB_F16,                 "F16"},
        {KB_F17,                 "F17"},
        {KB_F18,                 "F18"},
        {KB_F19,                 "F19"},
        {KB_F20,                 "F20"},
        {KB_F21,                 "F21"},
        {KB_F22,                 "F22"},
        {KB_F23,                 "F23"},
        {KB_F24,                 "F24"},
        {KB_0x88,                "0x88"},
        {KB_0x89,                "0x89"},
        {KB_0x8A,                "0x8A"},
        {KB_0x8B,                "0x8B"},
        {KB_0x8C,                "0x8C"},
        {KB_0x8D,                "0x8D"},
        {KB_0x8E,                "0x8E"},
        {KB_0x8F,                "0x8F"},
        {KB_NUMLOCK,             "NUMLOCK"},
        {KB_SCROLL,              "SCROLL"},
        {KB_0x92,                "0x92"},
        {KB_0x93,                "0x93"},
        {KB_0x94,                "0x94"},
        {KB_0x95,                "0x95"},
        {KB_0x96,                "0x96"},
        {KB_0x97,                "0x97"},
        {KB_0x98,                "0x98"},
        {KB_0x99,                "0x99"},
        {KB_0x9A,                "0x9A"},
        {KB_0x9B,                "0x9B"},
        {KB_0x9C,                "0x9C"},
        {KB_0x9D,                "0x9D"},
        {KB_0x9E,                "0x9E"},
        {KB_0x9F,                "0x9F"},
        {KB_LSHIFT,              "Left SHIFT"},
        {KB_RSHIFT,              "Right SHIFT"},
        {KB_LCONTROL,            "Left CONTROL"},
        {KB_RCONTROL,            "Right CONTROL"},
        {KB_LMENU,               "Left Alt"},
        {KB_RMENU,               "Right Alt"},
        {KB_BROWSER_BACK,        "BROWSER_BACK"},
        {KB_BROWSER_FORWARD,     "BROWSER_FORWARD"},
        {KB_BROWSER_REFRESH,     "BROWSER_REFRESH"},
        {KB_BROWSER_STOP,        "BROWSER_STOP"},
        {KB_BROWSER_SEARCH,      "BROWSER_SEARCH"},
        {KB_BROWSER_FAVORITES,   "BROWSER_FAVORITES"},
        {KB_BROWSER_HOME,        "BROWSER_HOME"},
        {KB_VOLUME_MUTE,         "VOLUME_MUTE"},
        {KB_VOLUME_DOWN,         "VOLUME_DOWN"},
        {KB_VOLUME_UP,           "VOLUME_UP"},
        {KB_MEDIA_NEXT_TRACK,    "MEDIA_NEXT_TRACK"},
        {KB_MEDIA_PREV_TRACK,    "MEDIA_PREV_TRACK"},
        {KB_MEDIA_STOP,          "MEDIA_STOP"},
        {KB_MEDIA_PLAY_PAUSE,    "MEDIA_PLAY_PAUSE"},
        {KB_LAUNCH_MAIL,         "LAUNCH_MAIL"},
        {KB_LAUNCH_MEDIA_SELECT, "LAUNCH_MEDIA_SELECT"},
        {KB_LAUNCH_APP1,         "LAUNCH_APP1"},
        {KB_LAUNCH_APP2,         "LAUNCH_APP2"},
        {KB_0xB8,                "0xB8"},
        {KB_0xB9,                "0xB9"},
        {KB_OEM_1,               "OEM_1"},
        {KB_OEM_PLUS,            "OEM_PLUS"},
        {KB_OEM_COMMA,           "OEM_COMMA"},
        {KB_OEM_MINUS,           "OEM_MINUS"},
        {KB_OEM_PERIOD,          "OEM_PERIOD"},
        {KB_OEM_2,               "OEM_2"},
        {KB_OEM_3,               "OEM_3"},
        {KB_0xC1,                "0xC1"},
        {KB_0xC2,                "0xC2"},
        {KB_0xC3,                "0xC3"},
        {KB_0xC4,                "0xC4"},
        {KB_0xC5,                "0xC5"},
        {KB_0xC6,                "0xC6"},
        {KB_0xC7,                "0xC7"},
        {KB_0xC8,                "0xC8"},
        {KB_0xC9,                "0xC9"},
        {KB_0xCA,                "0xCA"},
        {KB_0xCB,                "0xCB"},
        {KB_0xCC,                "0xCC"},
        {KB_0xCD,                "0xCD"},
        {KB_0xCE,                "0xCE"},
        {KB_0xCF,                "0xCF"},
        {KB_0xD0,                "0xD0"},
        {KB_0xD1,                "0xD1"},
        {KB_0xD2,                "0xD2"},
        {KB_0xD3,                "0xD3"},
        {KB_0xD4,                "0xD4"},
        {KB_0xD5,                "0xD5"},
        {KB_0xD6,                "0xD6"},
        {KB_0xD7,                "0xD7"},
        {KB_0xD8,                "0xD8"},
        {KB_0xD9,                "0xD9"},
        {KB_0xDA,                "0xDA"},
        {KB_OEM_4,               "OEM_4"},
        {KB_OEM_5,               "OEM_5"},
        {KB_OEM_6,               "OEM_6"},
        {KB_OEM_7,               "OEM_7"},
        {KB_OEM_8,               "OEM_8"},
        {KB_0xE0,                "0xE0"},
        {KB_0xE1,                "0xE1"},
        {KB_OEM_102,             "OEM_102"},
        {KB_0xE3,                "0xE3"},
        {KB_0xE4,                "0xE4"},
        {KB_PROCESSKEY,          "PROCESSKEY"},
        {KB_0xE6,                "0xE6"},
        {KB_PACKET,              "PACKET"},
        {KB_0xE8,                "0xE8"},
        {KB_0xE9,                "0xE9"},
        {KB_0xEA,                "0xEA"},
        {KB_0xEB,                "0xEB"},
        {KB_0xEC,                "0xEC"},
        {KB_0xED,                "0xED"},
        {KB_0xEE,                "0xEE"},
        {KB_0xEF,                "0xEF"},
        {KB_0xF0,                "0xF0"},
        {KB_0xF1,                "0xF1"},
        {KB_0xF2,                "0xF2"},
        {KB_0xF3,                "0xF3"},
        {KB_0xF4,                "0xF4"},
        {KB_0xF5,                "0xF5"},
        {KB_ATTN,                "ATTN"},
        {KB_CRSEL,               "CRSEL"},
        {KB_EXSEL,               "EXSEL"},
        {KB_EREOF,               "EREOF"},
        {KB_PLAY,                "PLAY"},
        {KB_ZOOM,                "ZOOM"},
        {KB_0xFC,                "0xFC"},
        {KB_PA1,                 "PA1"},
        {KB_OEM_CLEAR,           "OEM_CLEAR"},
        {KB_0xFF,                "0xFF"}
};