#pragma once

enum DialogStyle
{
	DIALOG_STYLE_MSGBOX						= 0,
	DIALOG_STYLE_INPUT						= 1,
	DIALOG_STYLE_LIST						= 2,
	DIALOG_STYLE_PASSWORD					= 3,
	DIALOG_STYLE_TABLIST					= 4,
	DIALOG_STYLE_TABLIST_HEADERS			= 5
};

enum Gamestate
{
	GAMESTATE_NONE							= 0,
	GAMESTATE_WAIT_CONNECT					= 9,
	GAMESTATE_DISCONNECTED					= 13,
	GAMESTATE_AWAIT_JOIN					= 15,
	GAMESTATE_CONNECTED						= 14,
	GAMESTATE_RESTARTING					= 18
};

enum PlayerState
{
	PLAYER_STATE_NONE						= 0,
	PLAYER_STATE_ONFOOT						= 17,
	PLAYER_STATE_PASSENGER					= 18,
	PLAYER_STATE_DRIVER						= 19,
	PLAYER_STATE_WASTED						= 32,
	PLAYER_STATE_SPAWNED					= 33
};

enum Limits
{
	SAMP_MAX_ACTORS							= 1000,
	SAMP_MAX_PLAYERS						= 1004,
	SAMP_MAX_VEHICLES						= 2000,
	SAMP_MAX_PICKUPS						= 4096,
	SAMP_MAX_OBJECTS						= 1000,
	SAMP_MAX_GANGZONES						= 1024,
	SAMP_MAX_3DTEXTS						= 2048,
	SAMP_MAX_TEXTDRAWS						= 2048,
	SAMP_MAX_PLAYERTEXTDRAWS				= 256,
	SAMP_MAX_CLIENTCMDS						= 144,
	SAMP_MAX_MENUS							= 128,
	SAMP_MAX_PLAYER_NAME					= 24,
	SAMP_ALLOWED_PLAYER_NAME_LENGTH			= 20
};

enum ChatMessageType
{
	CHAT_TYPE_NONE							= 0,
	CHAT_TYPE_CHAT							= 2,
	CHAT_TYPE_INFO							= 4,
	CHAT_TYPE_DEBUG							= 8
};

enum ChatDisplayMode
{
	CHAT_WINDOW_MODE_OFF					= 0,
	CHAT_WINDOW_MODE_LIGHT					= 1,
	CHAT_WINDOW_MODE_FULL					= 2
};

enum eSendrateType
{
	ONFOOTSENDRATE							= 1,
	INCARSENDRATE							= 2,
	AIMSENDRATE								= 3
};